$kind: http-example
request:
  url: "{{baseUrl}}/api/products/delete/:product_id"
  method: DELETE
  pathVariables:
    - key: product_id
      value: "2348"
      disabled: false
      description: Product ID to delete
  body:
    type: text
    content: ""
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: ""
order: 1000
