$kind: http-example
request:
  url: "{{baseUrl}}/api/products/add"
  method: POST
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "id": 833,
        "name": "string",
        "price": 3052.1084346280736,
        "description": "string"
      }
response:
  statusCode: 201
  statusText: Created
  body:
    type: text
    content: ""
order: 1000
